version: '3.7'

services:

  # ---------------------------------
  # Postgres (Dagster metadata)
  # ---------------------------------
  docker_example_postgresql:
    image: postgres:11
    container_name: docker_example_postgresql
    environment:
      POSTGRES_USER: 'postgres_user'
      POSTGRES_PASSWORD: 'postgres_password'
      POSTGRES_DB: 'postgres_db'
    networks:
      - docker_example_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres_user -d postgres_db']
      interval: 10s
      timeout: 8s
      retries: 5

  # ---------------------------------
  # Postgres (Iceberg JDBC catalog)
  # ---------------------------------
  iceberg_metastore:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: iceberg
    volumes:
      - ./infra/sql/iceberg-catalog-setup.sql:/docker-entrypoint-initdb.d/iceberg-catalog-setup.sql
    networks:
      - docker_example_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres-user -d iceberg"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ---------------------------------
  # MinIO (S3 storage)
  # ---------------------------------
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - docker_example_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minio-user minio-password;
      mc mb local/thailand-election2026;
      exit 0;
      "
    networks:
      - docker_example_network
  # ---------------------------------
  # Trino
  # ---------------------------------
  trino:
    image: trinodb/trino:479
    container_name: trino
    hostname: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
    networks:
      - docker_example_network
    depends_on:
      iceberg_metastore:
        condition: service_healthy
      minio:
        condition: service_healthy

  # ---------------------------------
  # Iceberg Migration (Create Tables)
  # ---------------------------------
  migration:
    image: trinodb/trino:479
    container_name: iceberg_migration
    networks:
      - docker_example_network
    depends_on:
      trino:
        condition: service_healthy
      create-bucket:
        condition: service_completed_successfully
    volumes:
      - ./infra/sql:/migrations
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for Trino...';
      until curl -s http://trino:8080/v1/info > /dev/null; do
        sleep 3;
      done;
      echo 'Running Iceberg migration...';
      trino --server http://trino:8080 --file /migrations/iceberg-table-setup.sql;
      echo 'Migration done.';
      "
  
  # ---------------------------------
  # Dagster user code
  # ---------------------------------
  docker_example_user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_user_code
    container_name: docker_example_user_code
    image: docker_example_user_code_image
    restart: always
    env_file:
      - .env
    environment:
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'postgres_password'
      DAGSTER_POSTGRES_DB: 'postgres_db'
      DAGSTER_CURRENT_IMAGE: 'docker_example_user_code_image'
      TRINO_HOST: trino
      TRINO_PORT: 8080
    networks:
      - docker_example_network
    volumes:
      - .:/opt/dagster/app
    depends_on:
      trino:
        condition: service_started

  # ---------------------------------
  # Dagster Webserver
  # ---------------------------------
  docker_example_webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - '0.0.0.0'
      - -p
      - '3000'
      - -w
      - workspace.yaml
    container_name: docker_example_webserver
    ports:
      - '3000:3000'
    environment:
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'postgres_password'
      DAGSTER_POSTGRES_DB: 'postgres_db'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - docker_example_network
    depends_on:
      docker_example_postgresql:
        condition: service_healthy
      docker_example_user_code:
        condition: service_started

  # ---------------------------------
  # Dagster Daemon
  # ---------------------------------
  docker_example_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: docker_example_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: 'postgres_user'
      DAGSTER_POSTGRES_PASSWORD: 'postgres_password'
      DAGSTER_POSTGRES_DB: 'postgres_db'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - docker_example_network
    depends_on:
      docker_example_postgresql:
        condition: service_healthy
      docker_example_user_code:
        condition: service_started

networks:
  docker_example_network:
    driver: bridge
    name: docker_example_network